import type { MatchDefinition, MatchEvent, Player, Team } from "./types";

const p = (id: string, name: string, shortName: string, position: string, number?: number, captain = false): Player => ({ id, name, shortName, position, number, captain });
const ev = (matchId: string, id: string, minute: number, second: number, type: MatchEvent["type"], commentary: string, extra: Partial<MatchEvent> = {}): MatchEvent => ({ id, matchId, minute, second, period: minute < 46 ? 1 : 2, displayMinute: minute === 0 ? "00′" : `${minute}′`, type, commentary, dataStatus: "confirmed", ...extra });
const team = (id: string, name: string, shortName: string, color: string, secondary: string, formation: string, starters: Player[], substitutes: Player[]): Team => ({ id, name, shortName, color, secondary, formation, starters, substitutes });

const unitedPsg = team("mufc", "Manchester United", "Man Utd", "#e31b23", "#f7d117", "4-2-3-1", [
  p("m-heaton", "Tom Heaton", "Heaton", "GK", 22), p("m-mazraoui", "Noussair Mazraoui", "Mazraoui", "RB", 3), p("m-maguire", "Harry Maguire", "Maguire", "CB", 5, true), p("m-heaven", "Ayden Heaven", "Heaven", "CB", 26), p("m-shaw", "Luke Shaw", "Shaw", "LB", 23), p("m-santos", "Andrey Santos", "Santos", "CM", 17), p("m-mount", "Mason Mount", "Mount", "CM", 7), p("m-amad", "Amad Diallo", "Amad", "RAM", 16), p("m-lacey", "Shea Lacey", "Lacey", "CAM", 46), p("m-dorgu", "Patrick Dorgu", "Dorgu", "LAM", 13), p("m-mbeumo", "Bryan Mbeumo", "Mbeumo", "ST", 19),
], [p("m-mee", "Dermot Mee", "Mee", "GK"), p("m-heath", "Fred Heath", "Heath", "GK"), p("m-amass", "Harry Amass", "Amass", "DF"), p("m-armer", "Daniel Armer", "Armer", "DF"), p("m-dalot", "Diogo Dalot", "Dalot", "DF"), p("m-yoro", "Leny Yoro", "Yoro", "DF"), p("m-bruno", "Bruno Fernandes", "Fernandes", "MF"), p("m-jfletcher", "Jack Fletcher", "J Fletcher", "MF"), p("m-tfletcher", "Tyler Fletcher", "T Fletcher", "MF"), p("m-tielemans", "Youri Tielemans", "Tielemans", "MF"), p("m-zirkzee", "Joshua Zirkzee", "Zirkzee", "FW")]);
const psg = team("psg", "Paris Saint-Germain", "PSG", "#12264b", "#e30613", "4-3-3", [
  p("p-safonov", "Matvey Safonov", "Safonov", "GK"), p("p-boly", "Boly", "Boly", "RB"), p("p-zabarnyi", "Illia Zabarnyi", "Zabarnyi", "CB"), p("p-pacho", "Willian Pacho", "Pacho", "CB"), p("p-koukaba", "Koukaba", "Koukaba", "LB"), p("p-dro", "Dro Fernández", "Fernández", "CM"), p("p-beraldo", "Lucas Beraldo", "Beraldo", "CM"), p("p-mayulu", "Senny Mayulu", "Mayulu", "CM"), p("p-mbaye", "Ibrahim Mbaye", "Mbaye", "RW"), p("p-ayari", "Ayari", "Ayari", "ST"), p("p-khvicha", "Khvicha Kvaratskhelia", "Kvaratskhelia", "LW"),
], ["Marquinhos","Nuno Mendes","Lucea","Vitinha","João Neves","Abo El Nay","Idder","Fanne Drame","Bourdin","Ndjantou","Meite","Longoni","Lucas Chevalier"].map((name, i) => p(`p-sub-${i}`, name, name.split(" ").at(-1)!, i === 12 ? "GK" : "SUB")));

const psgId = "psg-man-utd-2026";
const psgEvents: MatchEvent[] = [
  ev(psgId,"p-kick",0,0,"kickoff","Kick-off at Ullevi Stadium. Both teams settle into their starting shapes."),
  ev(psgId,"p-goal-1",2,14,"goal","Ibrahim Mbaye finishes from close range after Dro Fernández releases a quick cross.",{teamId:"psg",playerId:"p-mbaye",secondaryPlayerId:"p-dro",start:{x:100,y:29},end:{x:105,y:32},outcome:"goal",xg:.31}),
  ev(psgId,"p-yellow",16,20,"yellow-card","Ayden Heaven is booked for a high challenge on Khvicha Kvaratskhelia.",{teamId:"mufc",playerId:"m-heaven"}),
  ev(psgId,"p-sub-mount",20,5,"substitution","Mason Mount leaves after a knock; Tyler Fletcher replaces him.",{teamId:"mufc",playerId:"m-mount",secondaryPlayerId:"m-tfletcher"}),
  ev(psgId,"p-goal-2",32,18,"goal","Bryan Mbeumo drives a low left-footed finish beyond Safonov after Amad's pass.",{teamId:"mufc",playerId:"m-mbeumo",secondaryPlayerId:"m-amad",start:{x:89,y:39},end:{x:105,y:35},outcome:"goal",xg:.19}),
  ev(psgId,"p-ht",45,0,"half-time","Half-time: PSG 1–1 Manchester United."),
  ev(psgId,"p-sh-maz",45,10,"substitution","Diogo Dalot replaces Noussair Mazraoui at half-time.",{teamId:"mufc",playerId:"m-mazraoui",secondaryPlayerId:"m-dalot",dataStatus:"estimated"}),
  ev(psgId,"p-sh-heaven",45,12,"substitution","Leny Yoro replaces Ayden Heaven at half-time.",{teamId:"mufc",playerId:"m-heaven",secondaryPlayerId:"m-yoro",dataStatus:"estimated"}),
  ev(psgId,"p-heaton",49,8,"injury","Tom Heaton cannot continue after an injury.",{teamId:"mufc",playerId:"m-heaton"}),
  ev(psgId,"p-mee",49,40,"substitution","Dermot Mee replaces the injured Tom Heaton.",{teamId:"mufc",playerId:"m-heaton",secondaryPlayerId:"m-mee"}),
  ev(psgId,"p-tielemans",62,0,"substitution","Youri Tielemans enters for his Manchester United debut.",{teamId:"mufc",playerId:"m-dorgu",secondaryPlayerId:"m-tielemans",dataStatus:"estimated"}),
  ev(psgId,"p-bruno",64,0,"substitution","Bruno Fernandes replaces Shea Lacey.",{teamId:"mufc",playerId:"m-lacey",secondaryPlayerId:"m-bruno",dataStatus:"estimated"}),
  ev(psgId,"p-shaw",64,10,"substitution","Harry Amass replaces Luke Shaw.",{teamId:"mufc",playerId:"m-shaw",secondaryPlayerId:"m-amass",dataStatus:"estimated"}),
  ev(psgId,"p-mbeumo-off",64,20,"substitution","Joshua Zirkzee replaces Bryan Mbeumo.",{teamId:"mufc",playerId:"m-mbeumo",secondaryPlayerId:"m-zirkzee",dataStatus:"estimated"}),
  ev(psgId,"p-santos-off",65,5,"substitution","Jack Fletcher replaces Andrey Santos.",{teamId:"mufc",playerId:"m-santos",secondaryPlayerId:"m-jfletcher",dataStatus:"estimated"}),
  ev(psgId,"p-amad-off",65,15,"substitution","Daniel Armer replaces Amad Diallo.",{teamId:"mufc",playerId:"m-amad",secondaryPlayerId:"m-armer",dataStatus:"estimated"}),
  ev(psgId,"p-ft",90,0,"full-time","Full-time: PSG 1–1 Manchester United."),
];

const unitedLeeds = team("mufc", "Manchester United", "Man Utd", "#e31b23", "#f7d117", "4-2-3-1", [p("u-lammens","Senne Lammens","Lammens","GK"),p("u-yoro","Leny Yoro","Yoro","CB"),p("u-martinez","Lisandro Martínez","Martínez","CB"),p("u-mazraoui","Noussair Mazraoui","Mazraoui","RB"),p("u-shaw","Luke Shaw","Shaw","LB"),p("u-ugarte","Manuel Ugarte","Ugarte","CM"),p("u-casemiro","Casemiro","Casemiro","CM"),p("u-amad","Amad Diallo","Amad","RAM"),p("u-bruno","Bruno Fernandes","Fernandes","CAM",undefined,true),p("u-cunha","Matheus Cunha","Cunha","LAM"),p("u-sesko","Benjamin Sesko","Sesko","ST")], ["Diogo Dalot","Bryan Mbeumo","Tyler Fletcher","Altay Bayındır","Mason Mount","Shea Lacey","Ayden Heaven","Joshua Zirkzee","Tyrell Malacia"].map((name,i)=>p(`u-sub-${i}`,name,name.split(" ").at(-1)!,i===3?"GK":"SUB")));
const leeds = team("leeds","Leeds United","Leeds","#f5f5f0","#f6d32d","3-4-2-1",[p("l-darlow","Karl Darlow","Darlow","GK"),p("l-bijol","Jaka Bijol","Bijol","CB"),p("l-struijk","Pascal Struijk","Struijk","CB"),p("l-justin","James Justin","Justin","CB"),p("l-bogle","Jayden Bogle","Bogle","RWB"),p("l-ampadu","Ethan Ampadu","Ampadu","CM",undefined,true),p("l-tanaka","Ao Tanaka","Tanaka","CM"),p("l-gudmundsson","Gabriel Gudmundsson","Gudmundsson","LWB"),p("l-aaronson","Brenden Aaronson","Aaronson","AM"),p("l-okafor","Noah Okafor","Okafor","AM"),p("l-dcl","Dominic Calvert-Lewin","Calvert-Lewin","ST")],["Wilfried Gnonto","Ilia Gruev","Sean Longstaff","Sam Byram","Lukas Nmecha","Lucas Perri","Sebastiaan Bornauw","Joël Piroe","Facundo Buonanotte"].map((name,i)=>p(`l-sub-${i}`,name,name.split(" ").at(-1)!,i===5?"GK":"SUB")));
const leedsId="man-utd-leeds-2026";
const leedsEvents: MatchEvent[]=[
  ev(leedsId,"l-kick",0,0,"kickoff","Kick-off at Old Trafford."), ev(leedsId,"l-dcl-miss",3,8,"shot","Dominic Calvert-Lewin misses an early high-quality chance.",{teamId:"leeds",playerId:"l-dcl",start:{x:92,y:34},end:{x:105,y:41},outcome:"off-target",xg:.36}),
  ev(leedsId,"l-goal-1",5,22,"goal","Noah Okafor pounces on a poor clearance and scores for Leeds.",{teamId:"leeds",playerId:"l-okafor",start:{x:91,y:31},end:{x:105,y:33},outcome:"goal",xg:.28}),
  ev(leedsId,"l-goal-2",29,14,"goal","Noah Okafor strikes a volley from outside the area after United fail to clear.",{teamId:"leeds",playerId:"l-okafor",start:{x:82,y:28},end:{x:105,y:36},outcome:"goal",xg:.08}),
  ev(leedsId,"l-tanaka-line",44,18,"shot","Ao Tanaka's attempt is cleared off the line by Lisandro Martínez.",{teamId:"leeds",playerId:"l-tanaka",secondaryPlayerId:"u-martinez",start:{x:94,y:39},end:{x:104,y:37},outcome:"blocked",xg:.25}), ev(leedsId,"l-ht",45,0,"half-time","Half-time: Manchester United 0–2 Leeds United."),
  ev(leedsId,"l-red",56,10,"red-card","Lisandro Martínez is shown a straight red card after VAR review.",{teamId:"mufc",playerId:"u-martinez"}),
  ev(leedsId,"l-goal-3",69,3,"goal","Casemiro powers a header in from Bruno Fernandes' cross.",{teamId:"mufc",playerId:"u-casemiro",secondaryPlayerId:"u-bruno",start:{x:96,y:35},end:{x:105,y:31},outcome:"goal",xg:.21}),
  ev(leedsId,"l-sub-dalot",70,0,"substitution","Diogo Dalot replaces Noussair Mazraoui.",{teamId:"mufc",playerId:"u-mazraoui",secondaryPlayerId:"u-sub-0"}), ev(leedsId,"l-sub-mbeumo",70,8,"substitution","Bryan Mbeumo replaces Amad Diallo.",{teamId:"mufc",playerId:"u-amad",secondaryPlayerId:"u-sub-1"}), ev(leedsId,"l-sub-gnonto",74,0,"substitution","Wilfried Gnonto replaces Noah Okafor.",{teamId:"leeds",playerId:"l-okafor",secondaryPlayerId:"l-sub-0"}), ev(leedsId,"l-sub-gruev",74,8,"substitution","Ilia Gruev replaces Ao Tanaka.",{teamId:"leeds",playerId:"l-tanaka",secondaryPlayerId:"l-sub-1"}),
  ev(leedsId,"l-cas-line",85,4,"shot","Casemiro's header is cleared off the line by Calvert-Lewin.",{teamId:"mufc",playerId:"u-casemiro",secondaryPlayerId:"l-dcl",start:{x:97,y:34},end:{x:104,y:34},outcome:"blocked",xg:.29}), ev(leedsId,"l-ugarte-block",85,10,"shot","Calvert-Lewin blocks Manuel Ugarte's follow-up.",{teamId:"mufc",playerId:"u-ugarte",secondaryPlayerId:"l-dcl",start:{x:91,y:38},end:{x:97,y:35},outcome:"blocked",xg:.09}), ev(leedsId,"l-sub-longstaff",86,0,"substitution","Sean Longstaff replaces Brenden Aaronson.",{teamId:"leeds",playerId:"l-aaronson",secondaryPlayerId:"l-sub-2"}), ev(leedsId,"l-ft",90,0,"full-time","Full-time: Manchester United 1–2 Leeds United."),
];

export const MATCHES: MatchDefinition[]=[{
  id:psgId,seed:80826,date:"2026-08-08",competition:"Pre-season Club Friendly",venue:"Ullevi Stadium · Gothenburg, Sweden",home:psg,away:unitedPsg,finalScore:[1,1],halfTimeScore:[1,1],confirmedEvents:psgEvents,coverage:"Goals, one card, known substitutions and aggregate team statistics",statistics:{possession:{psg:59,mufc:41},shots:{psg:6,mufc:14},shotsOnTarget:{psg:3,mufc:7},corners:{psg:3,mufc:3},fouls:{psg:7,mufc:12},yellowCards:{psg:0,mufc:1},redCards:{psg:0,mufc:0},saves:{psg:6,mufc:2}},sources:[{label:"ESPN report",url:"https://www.espn.com/soccer/story/_/id/49561712/manchester-united-hold-psg-draw-bryan-mbeumo-shines-again"},{label:"Sports Mole",url:"https://www.sportsmole.co.uk/football/man-utd/result/in-good-shape-man-utd-again-impress-in-draw-with-european-champions-psg_602660.html"},{label:"Sky Sports teams",url:"https://www.skysports.com/football/paris-saint-germain-vs-manchester-united/teams/555766"}]},{
  id:leedsId,seed:41326,date:"2026-04-13",competition:"Premier League",venue:"Old Trafford · Manchester",home:unitedLeeds,away:leeds,finalScore:[1,2],halfTimeScore:[0,2],confirmedEvents:leedsEvents,coverage:"Lineups, goals, red card, substitutions and published aggregate statistics",statistics:{possession:{mufc:53,leeds:47},shots:{mufc:20,leeds:15},shotsOnTarget:{mufc:9,leeds:6},corners:{mufc:11,leeds:4},fouls:{mufc:12,leeds:15},yellowCards:{mufc:3,leeds:2},redCards:{mufc:1,leeds:0},xg:{mufc:1.31,leeds:2.37},saves:{mufc:3,leeds:6}},sources:[{label:"ESPN match",url:"https://www.espn.com/soccer/match/_/gameId/740912"},{label:"Sky Sports report",url:"https://www.skysports.com/football/man-utd-vs-leeds/report/531445"},{label:"beIN Sports",url:"https://www.beinsports.com/en-us/soccer/premier-league/articles/manchester-united-1-2-leeds-united-okafor-double-secures-first-old-trafford-win-since-1981-2026-04-13"}] }];
export const MATCH_BY_ID=Object.fromEntries(MATCHES.map(match=>[match.id,match]));
