import type { RuntimeEnv } from "@/lib/server/database";

const FPL_URL="https://fantasy.premierleague.com/api/bootstrap-static/";
type FplTeam={id:number;name:string;short_name:string;code:number};
type FplPlayer={id:number;team:number;web_name:string;first_name:string;second_name:string;element_type:number;now_cost:number;total_points:number;form:string;selected_by_percent:string;minutes:number;goals_scored:number;assists:number;clean_sheets:number;goals_conceded:number;yellow_cards:number;red_cards:number;saves:number;bonus:number;bps:number;influence:string;creativity:string;threat:string;ict_index:string;expected_goals:string;expected_assists:string;expected_goal_involvements:string;expected_goals_conceded:string;status:string;chance_of_playing_next_round:number|null;news:string};

export async function ensurePlayerIntelligenceTables(db:D1Database){await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS player_entities (id TEXT PRIMARY KEY, canonical_name TEXT NOT NULL, short_name TEXT NOT NULL, team_id TEXT NOT NULL, position TEXT NOT NULL, updated_at TEXT NOT NULL)`),
  db.prepare(`CREATE TABLE IF NOT EXISTS player_aliases (player_id TEXT NOT NULL, provider TEXT NOT NULL, provider_id TEXT NOT NULL, alias TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(provider,provider_id))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS player_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT, player_id TEXT NOT NULL, provider TEXT NOT NULL, observed_at TEXT NOT NULL, season TEXT NOT NULL, payload_json TEXT NOT NULL, confidence REAL NOT NULL, source_url TEXT NOT NULL, UNIQUE(player_id,provider,observed_at))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS player_metric_values (player_id TEXT NOT NULL, metric_key TEXT NOT NULL, metric_version TEXT NOT NULL, value REAL NOT NULL, confidence REAL NOT NULL, sample_minutes INTEGER NOT NULL, cohort TEXT NOT NULL, observed_at TEXT NOT NULL, PRIMARY KEY(player_id,metric_key,metric_version,observed_at))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS intelligence_sync_runs (id INTEGER PRIMARY KEY AUTOINCREMENT, provider TEXT NOT NULL, started_at TEXT NOT NULL, finished_at TEXT NOT NULL, status TEXT NOT NULL, entities INTEGER NOT NULL, issues INTEGER NOT NULL, note TEXT NOT NULL DEFAULT '')`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_player_snapshots_player_time ON player_snapshots(player_id,observed_at DESC)`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_metric_player_time ON player_metric_values(player_id,observed_at DESC)`),
])}

const slug=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const n=(v:string|number|null|undefined)=>Number(v)||0;
const clamp=(v:number)=>Math.max(0,Math.min(100,v));
function metrics(p:FplPlayer){const mins=Math.max(1,p.minutes),per90=90/mins,availability=p.status==="a"?100:p.chance_of_playing_next_round??35;return {
  control:clamp(n(p.creativity)*.12+n(p.influence)*.06+n(p.bps)*.025),
  threat:clamp(n(p.threat)*.11+(n(p.expected_goals)+n(p.expected_assists))*per90*34),
  output:clamp((p.goals_scored+p.assists)*per90*28+n(p.expected_goal_involvements)*per90*22),
  reliability:clamp(Math.min(70,p.minutes/34)+availability*.3),
  momentum:clamp(n(p.form)*10+n(p.ict_index)*.15),
}}

export async function syncManchesterUnitedPlayers(env:RuntimeEnv){if(!env.DB)return {ok:false,reason:"no_database"};await ensurePlayerIntelligenceTables(env.DB);const started=new Date().toISOString();let count=0,issues=0;try{const response=await fetch(FPL_URL,{headers:{"user-agent":"GOG-Newsroom/1.0"}});if(!response.ok)throw new Error(`FPL ${response.status}`);const data=await response.json() as {teams:FplTeam[];elements:FplPlayer[]};const club=data.teams.find(t=>/manchester united/i.test(t.name)||t.short_name==="MUN");if(!club)throw new Error("Manchester United team not found");const observed=new Date().toISOString(),season=`${new Date().getUTCFullYear()}/${String(new Date().getUTCFullYear()+1).slice(-2)}`;for(const p of data.elements.filter(x=>x.team===club.id)){const id=slug(`${p.first_name}-${p.second_name}`),name=`${p.first_name} ${p.second_name}`.trim(),position=["GK","DEF","MID","FWD"][p.element_type-1]??"UNK",m=metrics(p);await env.DB.batch([
    env.DB.prepare(`INSERT INTO player_entities VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET canonical_name=excluded.canonical_name,short_name=excluded.short_name,position=excluded.position,updated_at=excluded.updated_at`).bind(id,name,p.web_name,"mufc",position,observed),
    env.DB.prepare(`INSERT INTO player_aliases VALUES(?,?,?,?,?) ON CONFLICT(provider,provider_id) DO UPDATE SET player_id=excluded.player_id,alias=excluded.alias`).bind(id,"fpl",String(p.id),p.web_name,observed),
    env.DB.prepare(`INSERT OR IGNORE INTO player_snapshots(player_id,provider,observed_at,season,payload_json,confidence,source_url) VALUES(?,?,?,?,?,?,?)`).bind(id,"fpl",observed,season,JSON.stringify(p),.82,FPL_URL),
    ...Object.entries(m).map(([key,value])=>env.DB!.prepare(`INSERT OR IGNORE INTO player_metric_values VALUES(?,?,?,?,?,?,?,?)`).bind(id,`gog_${key}`,"1.0.0",value,Math.min(.95,.45+p.minutes/3000*.5),p.minutes,`FPL ${position}`,observed)),
  ]);count++}await env.DB.prepare(`INSERT INTO intelligence_sync_runs(provider,started_at,finished_at,status,entities,issues,note) VALUES(?,?,?,?,?,?,?)`).bind("fpl",started,observed,"ok",count,issues,"Manchester United snapshot").run();return {ok:true,entities:count,observedAt:observed}}catch(error){issues++;const finished=new Date().toISOString();await env.DB.prepare(`INSERT INTO intelligence_sync_runs(provider,started_at,finished_at,status,entities,issues,note) VALUES(?,?,?,?,?,?,?)`).bind("fpl",started,finished,"error",count,issues,error instanceof Error?error.message:String(error)).run();return {ok:false,entities:count,error:error instanceof Error?error.message:String(error)}}}

export async function getPlayerIntelligence(env:RuntimeEnv){if(!env.DB)return {players:[],health:null};await ensurePlayerIntelligenceTables(env.DB);const players=await env.DB.prepare(`SELECT p.id,p.canonical_name,p.short_name,p.position,p.updated_at,s.payload_json FROM player_entities p LEFT JOIN player_snapshots s ON s.id=(SELECT id FROM player_snapshots WHERE player_id=p.id ORDER BY observed_at DESC LIMIT 1) WHERE p.team_id='mufc' ORDER BY p.position,p.canonical_name`).all<{id:string;canonical_name:string;short_name:string;position:string;updated_at:string;payload_json:string}>();const metrics=await env.DB.prepare(`SELECT player_id,metric_key,value,confidence,sample_minutes,cohort,observed_at FROM player_metric_values WHERE rowid IN (SELECT MAX(rowid) FROM player_metric_values GROUP BY player_id,metric_key)`).all<Record<string,unknown>>();const byPlayer=new Map<string,Record<string,unknown>>();for(const row of metrics.results??[]){const entry=byPlayer.get(String(row.player_id))??{};entry[String(row.metric_key)]={value:row.value,confidence:row.confidence,minutes:row.sample_minutes,cohort:row.cohort,observedAt:row.observed_at};byPlayer.set(String(row.player_id),entry)}const health=await env.DB.prepare(`SELECT provider,status,finished_at,entities,issues,note FROM intelligence_sync_runs ORDER BY id DESC LIMIT 1`).first();return {players:(players.results??[]).map(p=>({...p,profile:p.payload_json?JSON.parse(p.payload_json):null,metrics:byPlayer.get(p.id)??{}})),health,methodology:{version:"1.0.0",source:FPL_URL,status:"derived",warning:"GOG metrics are transparent derived indices, not official Premier League ratings."}}}
