import assert from "node:assert/strict";
import test from "node:test";
import { MATCHES } from "../features/replay/data.ts";
import { chartSeries, liveStats, positionsAt, reconstructMatch, stateAt, validateMatch } from "../features/replay/engine.ts";

test("reconstruction is deterministic for both matches",()=>{for(const definition of MATCHES){const left=reconstructMatch(definition),right=reconstructMatch(definition);assert.deepEqual(left.events,right.events);assert.deepEqual(left.minuteReports,right.minuteReports)}});
test("confirmed anchors and aggregate constraints are preserved",()=>{for(const definition of MATCHES){const match=reconstructMatch(definition);assert.equal(validateMatch(match),true);for(const anchor of definition.confirmedEvents)assert.deepEqual(match.events.find(event=>event.id===anchor.id),anchor);const stats=liveStats(match,match.duration);for(const team of [definition.home,definition.away]){const id=team.id;assert.equal(stats[id].shots,definition.statistics.shots[id]);assert.equal(stats[id].onTarget,definition.statistics.shotsOnTarget[id]);assert.equal(stats[id].corners,definition.statistics.corners[id]);assert.equal(stats[id].fouls,definition.statistics.fouls[id]);assert.equal(stats[id].yellow,definition.statistics.yellowCards[id]);assert.equal(stats[id].red,definition.statistics.redCards[id]);if(definition.statistics.xg)assert.equal(Number(stats[id].xg.toFixed(2)),definition.statistics.xg[id])}}});
test("score, substitutions and red card reconstruct correctly when seeking",()=>{for(const definition of MATCHES){const match=reconstructMatch(definition);assert.deepEqual(stateAt(match,match.duration).score,definition.finalScore)}const leeds=reconstructMatch(MATCHES[1]);const before=stateAt(leeds,56*60),after=stateAt(leeds,57*60);assert.equal(before.active.mufc.length,11);assert.equal(after.active.mufc.length,10);assert.ok(!after.active.mufc.includes("u-martinez"));const at71=stateAt(leeds,71*60);assert.ok(!at71.active.mufc.includes("u-amad"));assert.ok(at71.active.mufc.includes("u-sub-1"))});
test("all coordinates remain in bounds and minute reports are complete",()=>{for(const definition of MATCHES){const match=reconstructMatch(definition);assert.equal(match.minuteReports.length,91);assert.deepEqual(match.minuteReports.map(item=>item.minute),Array.from({length:91},(_,i)=>i));for(let time=0;time<=match.duration;time+=30){const frame=positionsAt(match,time);for(const point of [...Object.values(frame.players),frame.ball]){assert.ok(point.x>=0&&point.x<=105);assert.ok(point.y>=0&&point.y<=68)}}}});
test("analytics derive from the replay event stream",()=>{for(const definition of MATCHES){const match=reconstructMatch(definition),series=chartSeries(match),last=series.at(-1);assert.equal(series.length,91);assert.equal(last.home,Number(liveStats(match,match.duration)[definition.home.id].xg.toFixed(2)));assert.equal(last.away,Number(liveStats(match,match.duration)[definition.away.id].xg.toFixed(2)))}});
test("reconstructed actions never reference an inactive player",()=>{for(const definition of MATCHES){const match=reconstructMatch(definition);for(const event of match.events.filter(item=>item.dataStatus==="reconstructed"&&item.playerId)){const state=stateAt(match,event.minute*60+event.second-.01);assert.ok(state.active[event.teamId].includes(event.playerId),`${event.id} references inactive ${event.playerId}`)}}});
